src/DafDev.FootballManagerNot.GroupManagement.Web/Models/GroupViewModel.cs
namespace DafDev.FootballManagerNot.GroupManagement.Web.Models;

public class GroupViewModel
{
    public int Id { get; set; }
    public string? Name { get; set; }
}

src/DafDev.FootballManagerNot.GroupManagement.Web/Models/UserViewModel.cs
namespace DafDev.FootballManagerNot.GroupManagement.Web.Models;

public class UserViewModel
{
    public int Id { get; set; }
    public string? FirstName { get; set; }
    public string? Lastname { get; set; }
}

src/DafDev.FootballManagerNot.GroupManagement.Web/Controllers/GroupsController.cs
using DafDev.FootballManagerNot.GroupManagement.Contracts.Services;
using DafDev.FootballManagerNot.GroupManagement.Web.Models;
using DafDev.FootballManagerNot.GroupManagement.Web.Mappers;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace DafDev.FootballManagerNot.GroupManagement.Web.Controllers;

[Route("groups")]
public class GroupsController : Controller
{
    private readonly IGroupService _groupService;

    public GroupsController(IGroupService groupService)
    {
        _groupService = groupService;
    }

    [HttpGet]
    [Route("")]
    public IActionResult Index() => View(_groupService.GetAll().ToViewModel());

    [HttpGet]
    [Route("users")]
    public string AddUser(string name, int id = 0) => HtmlEncoder.Default.Encode($"User {name} with id {id} has been added.");

    [HttpGet]
    [Route("{id}")]
    public IActionResult Details(int id)
    {
        var group = _groupService.GetById(id);

        if (group is null)
            return NotFound();

        return View(group.ToViewModel());
    }

    [HttpPost]
    [Route("{id}")]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(GroupViewModel editGroup)
    {
        if (editGroup is null)
            return BadRequest();

        var group = _groupService.Update(editGroup.ToServiceModel());

        if (group is null)
            return NotFound();

        group.Name = editGroup.Name;

        return RedirectToAction("Index");
    }

    [HttpGet]
    [Route("create")]
    public IActionResult Create() => View();

    [HttpPost]
    [Route("create")]
    [ValidateAntiForgeryToken]
    public IActionResult Create(GroupViewModel model)
    {
        if (model == null)
            return BadRequest();

        _groupService.Add(model.ToServiceModel());

        return RedirectToAction("Index");
    }
}

src/DafDev.FootballManagerNot.GroupManagement.Web/Views/Groups/Create.cshtml
@model GroupViewModel

<form asp-controller="Groups" asp-action="Create" method="post">
    <label asp-for="Name">Name</label>
    <input asp-for="Name" />
    <button type="submit">Create</button>
</form>

src/DafDev.FootballManagerNot.GroupManagement.Web/Views/Groups/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model GroupViewModel

<h2>Details</h2>
<form asp-controller="Groups" asp-action="Edit" asp-route-id=@Model.Id method="post">
    <label asp-for="Name">Name</label>
    <input asp-for="Name"/>
    <button type ="submit">Save</button>
</form>

<p>group id: @Model.Id; group name: @Model.Name </p>

src/DafDev.FootballManagerNot.GroupManagement.Web/Views/Groups/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<GroupViewModel>
@{
    ViewData["Title"] = "Index";
}
<h2>Index</h2>

<p>Here are the groups</p>

<ul>
@foreach (var group in Model)
{
    <li>@group.Name <a asp-controller="Groups" asp-action="Details" asp-route-id=@group.Id>Edit</a></li>
}    
</ul>

<a asp-controller="Groups" asp-action="Create">Create</a>